name: CI/CD to ECS Fargate

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - main
    types:
      - completed
  workflow_call:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: llmopsraglive
  ECS_SERVICE: llmops-rag-live-service
  ECS_CLUSTER: llmops-rag-live-cluster
  ECS_TASK_DEFINITION: .github/workflows/task_definition.json
  CONTAINER_NAME: llmops-rag-live-container

permissions:
  id-token: write
  contents: read

jobs:

  # -------------------------------
  # 1. Check CI Status
  # -------------------------------
  check-status:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') }}

    steps:
      - name: CI passed on main branch
        run: echo "CI passed on main branch, proceeding to build and deploy."

  # -------------------------------
  # 2. Build & Push Docker Image
  # -------------------------------
  build-and-push:
    name: Build & Push Docker Image
    needs: [check-status]
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      
      - name: Inspect GitHub OIDC claims
        shell: bash
        run: |
          TOKEN_JSON=$(curl -sS \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r '.value')

          echo "$ID_TOKEN" |
            cut -d '.' -f2 |
            base64 -d 2>/dev/null |
            jq '{iss, aud, sub, repository, repository_id, repository_owner, repository_owner_id, ref, event_name}'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha || github.sha }}


        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

  # -------------------------------
  # 3. Deploy to ECS
  # -------------------------------
  deploy:
    name: Deploy to ECS Fargate
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::834015912477:role/GitHubActionsECSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Render Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.build-and-push.outputs.image }}

      - name: Print Rendered Task
        run: cat ${{ steps.render-task.outputs.task-definition }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Done!
        run: echo "Deployed to ECS Fargate Successfully"